### ISSUE TITLE
Can't build ios version

### ISSUE THREAD

**Issue by adantart** [ManifestWebDesign/twitter-connect-plugin#15]
```
** BUILD FAILED **


The following build commands failed:
	CompileC build/myproject.build/Debug-iphonesimulator/myproject.build/Objects-normal/i386/TwitterConnect.o myproject/Plugins/twitter-connect-plugin/TwitterConnect.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/home/myproject-app/platforms/ios/cordova/build-debug.xcconfig,-project,myproject.xcodeproj,ARCHS=i386,-target,myproject,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/home/myproject-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/home/myproject-app/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /home/myproject-app/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /home/myproject-app/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

any ideas ?

**Comment by TheBosZ** [comment]
Easy questions first: do you have Xcode and the command line utilities installed?

**Comment by adantart** [comment]
Yes and yes. I had to go through issue #10 process to install it ;-)
Also I have some personal Xcode projects.

**Comment by TheBosZ** [comment]
Darn. No easy solutions then. Have you tried the solutions in this thread? http://forum.ionicframework.com/t/ionic-build-ios-plugin-errors-exit-code-65/7274/32

If you're not using ionic, just replace the "ionic" command with "cordova"

**Comment by adantart** [comment]
I already did a project clean and removed/installed the plugin before coming here :P 
No solved ... 
Android is working though !

**Comment by TheBosZ** [comment]
Anyone else able to help out here?

**Comment by adantart** [comment]
TwitterKit doesn't support iOS 6.x and lower. Please, change your minimum deployment target to iOS 7.0

**Comment by TheBosZ** [comment]
I'll make a note in the documentation.
