### ISSUE TITLE
Exception: Must start Twitter Kit with Fabric.with() first

### ISSUE THREAD

**Issue by srkgupta** [ManifestWebDesign/twitter-connect-plugin#23]
Hi, 

I followed the steps you have mentioned and had integrated the Twitter Connect Plugin. However when I try to login via Twitter, I get the following exception and the application crashes. I am not sure what is missing here (or) if others have also faced this issue?
 
Fatal Exception: java.lang.IllegalStateException: Must start Twitter Kit with Fabric.with() first
       at com.twitter.sdk.android.Twitter.checkInitialized(Twitter.java:43)
       at com.twitter.sdk.android.Twitter.logIn(Twitter.java:87)
       at com.manifestwebdesign.twitterconnect.TwitterConnect$1.run(TwitterConnect.java:68)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by TheBosZ** [comment]
It's quite possible that Fabric, the Twitter SDK, has changed their requirements.

If I can, I'll see if I can get some time to figure out what's going on.

In the meantime, if any one can help, it would be appreciated.

**Comment by jelmervisser** [comment]
Is it possible that you are already use Fabric.with() somewhere else in your app, in MainActivity.java or so? Removing that fixed the error for me.

**Comment by emir-aydin-hs** [comment]
I'm having this issue as well. Any updates? @srkgupta @TheBosZ

**Comment by emiraydin** [comment]
I'm having this issue as well. Any updates? @srkgupta @TheBosZ

**Comment by TheBosZ** [comment]
@emiraydin can you try the fix from @jelmervisser ?

**Comment by emiraydin** [comment]
@TheBosZ I'm using this plugin: https://github.com/sarriaroman/FabricPlugin and it does have a call `Fabric.with`, but the build fails if I remove that or move it into `TwitterConnect.java`. There should be a way multiple `Fabric.with` calls can live together, no?

**Comment by TheBosZ** [comment]
If you remove the Fabric plugin, does this work correctly?

**Comment by jelmervisser** [comment]
It will work without that plugin. You need to add Twitter to the Fabric.with() in that plugin or completely remove it from both plugins and do it in the MainActivity of your own project.

**Comment by TheBosZ** [comment]
After reading the docs, it looks like this is the issue:

Fabric.with initializes Fabric.
Subsequent calls to Fabric.with are **ignored**
Since only one of the Fabric.with calls is honored, Twitter isn't added.
Since Twitter isn't added, the error you get occurs.

Now, I have no idea how to fix this in a way that will work for everyone. I can't find anything in the docs that talk about adding Twitter after Fabric is initialized.

I've [filed a request in the support forum](https://twittercommunity.com/t/adding-a-kit-to-fabric-after-initialization-with-fabric-with/71277); we'll see what the Fabric team says.

To temporarily make it work for you, you can edit the plugin files and change both Fabric.with to use **both** Twitter and Crashlytics kits.

**Comment by BanterClaus** [comment]
For anyone stumbling across this; simple solution is to modify your initial call to Fabric.with() to use both twitter and any other plugins (crashlytics for me). Can be done like so: 

```
        TwitterAuthConfig authConfig = new TwitterAuthConfig("KEY", "SECRET");
        Fabric.with(new Fabric.Builder(this).kits(new Crashlytics(), new Twitter(authConfig)).build());
```

**Comment by shawns582** [comment]
@BanterClaus I have the Fabric Plugin (cordova-fabric-plugin) and TwitterConnect installed.  What file do I make the recommended changes in? TwitterConnect.java? Do I do comment out the call to Fabric.with in FabricPlugin.java?  Also if that is for Android, what do I need to do for iOS?

Thanks!

**Comment by TitikshaDaga** [comment]
@shawns582  did u find an answer?

**Comment by shawns582** [comment]
I figured it out, but recently I stopped using Fabric temporarily bc it has been a pain to set up sometimes.  Either way here is what I did:

In platforms/android/src/com/sarriaroman/fabric/FabricPlugin.java:

add these imports:
import com.twitter.sdk.android.Twitter;
import com.twitter.sdk.android.core.*;

add these functions:

private String getTwitterKey() {
	return preferences.getString("TwitterConsumerKey", "");
}
private String getTwitterSecret() {
	return preferences.getString("TwitterConsumerSecret", "");
}

Use these lines inside of pluginInitialize():

Fabric.with(this.cordova.getActivity().getApplicationContext(), new Crashlytics(), new Answers(), new Twitter(new TwitterAuthConfig(getTwitterKey(), getTwitterSecret())));
Log.v("Fabric Init", "Initialize TwitterConnect, Crashlytics, Answers");

**Comment by guylando** [comment]
Newest twitterkit does not use fabric at all, try this version of the plugin:
It has the LATEST twitterkit sdks both for android and ios and fixes the various bugs existing in the other versions of this plugin. Also added info about some gotchas and important things to pay attention to in the readme. Enjoy: https://github.com/guylando/twitterkit3-plugin
Tested and works in latest ios and android
