### ISSUE TITLE
App crashing when I try to retrieve user profile

### ISSUE THREAD

**Issue by marvoh** [ManifestWebDesign/twitter-connect-plugin#36]
Hi, I am getting the error below after my app crashes.

`10-20 10:14:48.857  6129  6622 E AndroidRuntime: java.lang.IllegalArgumentException: Session must not be null.
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at com.twitter.sdk.android.core.TwitterApiClient.<init>(TwitterApiClient.java:39)
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at com.twitter.sdk.android.core.TwitterApiClient.<init>(TwitterApiClient.java:66)
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at com.manifestwebdesign.twitterconnect.TwitterConnect$UserServiceApi.<init>(TwitterConnect.java:106)
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at com.manifestwebdesign.twitterconnect.TwitterConnect$3.run(TwitterConnect.java:123)
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-20 10:14:48.857  6129  6622 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)`

Here is my code. I authenticate the user then try to pull his profile

`n.twitterSignIn = function()
    {
        TwitterConnect.login(
          function(result) {
            console.log('Successful login!');
            console.log(result);
          }, function(error) {
            console.log('Error logging in');
            console.log(error);
          }
        );
        getTwitterProfileInfo();
    }

    getTwitterProfileInfo = function()
    {
        TwitterConnect.showUser(
          function(result) {
            console.log('User Profile:');
            console.log(result);
            console.log('Twitter handle :'+result.userName);
          }, function(error) {
            console.log('Error retrieving user profile');
            console.log(error);
          }
        );
    }`

**Comment by ferdil** [comment]
Put the call to getTwitterProfileInfo inside the success callback. You're invoking the function outside the .login - methinks you need to read a bit more about callbacks.
```
n.twitterSignIn = function()
    {
        TwitterConnect.login(
          function(result) {
            console.log('Successful login!');
            console.log(result);
            getTwitterProfileInfo();
          }, function(error) {
            console.log('Error logging in');
            console.log(error);
          }
        );
    }
```
